FROM node:15-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY server/package*.json ./
RUN npm install --production

COPY server/. .
RUN npm run build

# tsc ignores *.graphql files
# See: https://github.com/ardatan/graphql-tools/issues/273
COPY server/src/schema.graphql ./build/schema.graphql

EXPOSE 3456

CMD node build/index.js
