FROM node:15-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY web/package*.json ./
RUN npm install --production

COPY web/. .
RUN npm install -g http-server

EXPOSE 5000

CMD http-server -p 5000 build
