kind: Deployment
metadata:
  name: posty-mongo
spec:
  selector:
    matchLabels:
      app: posty-server
  replicas: 1
  template:
    metadata:
      labels:
        app: posty-server
    spec:
      containers:
        - name: posty-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  labels:
    app: posty-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: posty-mongo
  labels:
    app: posty-server
spec:
  ports:
    - name: posty-mongo
      port: 27017
      targetPort: 27017
  type: NodePort
  selector:
    app: posty-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posty-server
spec:
  selector:
    matchLabels:
      app: posty-server
  replicas: 2
  template:
    metadata:
      labels:
        app: posty-server
    spec:
      containers:
        - name: posty-server
          image: lunush/posty-server:latest
          ports:
            - containerPort: 3456
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data
