apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: posty-cert-issuer
spec:
  acme:
    email: hi@lunu.sh
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: posty-cert-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
